# Generated by Django 4.0.4 on 2022-08-29 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_fllowerscount'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='style',
            field=models.IntegerField(null=True),
        ),
    ]
